// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/ansidev/fiber-starter-project/author/repository"
	"github.com/ansidev/fiber-starter-project/author/service"
	"github.com/ansidev/fiber-starter-project/pkg/db"
	repository2 "github.com/ansidev/fiber-starter-project/post/repository"
	service2 "github.com/ansidev/fiber-starter-project/post/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitSqlClient(config db.SqlDbConfig) *sql.DB {
	sqlDB := db.NewPostgresClient(config)
	return sqlDB
}

func InitAuthorService(db2 *gorm.DB) service.IAuthorService {
	iAuthorRepository := repository.NewPostgresAuthorRepository(db2)
	iAuthorService := service.NewAuthorService(iAuthorRepository)
	return iAuthorService
}

func InitPostService(db2 *gorm.DB) service2.IPostService {
	iPostRepository := repository2.NewPostgresPostRepository(db2)
	iPostService := service2.NewPostService(iPostRepository)
	return iPostService
}
